### ISSUE TITLE
WeaponData and a "npostal" resource?

### ISSUE THREAD

**Issue by Bagpackcat** [RoyaleWind/rw_hud_i#2]
![image](https://user-images.githubusercontent.com/107357837/205509822-1d851667-9e0b-4d11-8c65-77a0846ee18a.png)

**Comment by RoyaleWind** [comment]
WeaponData is in esx extended 1.2

**Comment by RoyaleWind** [comment]
and i just  put npostal at esx folder

**Comment by Bagpackcat** [comment]
is it possible if you could give me a link for your npostal? there are some but not the one it wants ^^
